# These substitutions allow the end user to override certain values
substitutions:
  devicename: pokypow
  upper_devicename: PokyPow

esphome:
  name: "${devicename}"
  friendly_name: PokyPow
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # Green light after boot
  on_boot:
    priority: -100  # Lower priority to ensure it runs after boot is complete
    then:
      - light.turn_on:
          id: led_strip
          red: 0
          green: 100%
          blue: 0
          brightness: 50%

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  framework:
    type: esp-idf


# Enable Home Assistant API
# api:
#   # Blue light after connected to Home Assistant
#   on_client_connected:
#     then:
#       - light.turn_on:
#           id: led_strip
#           red: 0
#           green: 0
#           blue: 100%
#           brightness: 50%
#   on_client_disconnected:
#     then:
#       - light.turn_on:
#           id: led_strip
#           red: 100%
#           green: 100%
#           blue: 0
#           brightness: 50%

# Example configuration entry
# uart:
#   baud_rate: 9600
#   port: /dev/tty.usbserial-1140


# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
  - platform: web_server


# Enable WiFi provisioning via USB/Serial after flashing
# Logger needs to be set to uart0 for this to work
improv_serial:

# To be able to get logs from the device via serial and api.
logger:
  # Change to the urat controler on board to make improve serial work for WiFi provisioning
  hardware_uart: uart0

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "PokyPow Setup"
  
  manual_ip:
    # static_ip: 192.168.178.174
    static_ip: 192.168.178.7
    gateway: 192.168.178.1
    subnet: 255.255.255.0



# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# 
web_server:
  port: 80
  include_internal: true

###
###  LED, Switchtes, etc.
###

light:
  - platform: neopixelbus
    type: GRBW
    variant: SK6812
    pin: GPIO5
    id: led_strip
    num_leds: 1
    name: "Gamer LED"
    effects:
      - addressable_rainbow:

# sensor:
#   - platform: wifi_signal
#     name: "WiFi Signal"
#     update_interval: 2s


switch:
  - platform: template
    name: "Lock Power Button"
    id: lock_power_button_switch
    icon: "mdi:lock"
    turn_on_action:
      - lambda: |-
          id(child_lock) = true;
    turn_off_action:
      - lambda: |-
          id(child_lock) = false;
    lambda: |-
      return id(child_lock);

      

  - platform: factory_reset
    name: Restart with Factory Default Settings
  
  - platform: gpio
    pin: 
      number: GPIO7
      inverted: true
      mode:
        output: true
        open_drain: true
        pulldown: false
        pullup: false
    id: esp32_power_out_mb
    internal: true

  - platform: gpio
    pin: 
      number: GPIO6
      # inverted: true
      mode:
        output: true
        pulldown: true
    id: esp32_reset_out_mb
    internal: true

  - platform: template
    name: "Power Switch"
    id: power_switch
    internal: true
    turn_on_action:
      - switch.turn_on: esp32_power_out_mb
      - delay: 1000ms
      - switch.turn_off: esp32_power_out_mb

  - platform: template
    name: "Power Switch Force"
    id: power_switch_force
    internal: true
    turn_on_action:
      - switch.turn_on: esp32_power_out_mb
      - delay: 10000ms
      - switch.turn_off: esp32_power_out_mb

  - platform: template
    name: "Reset Switch"
    id: reset_switch
    internal: true
    turn_on_action:
      - switch.turn_on: esp32_reset_out_mb
      - delay: 1000ms
      - switch.turn_off: esp32_reset_out_mb

globals:
  - id: child_lock
    type: bool
    restore_value: true
    initial_value: 'false'

output:
  - platform: gpio
    pin: GPIO4
    id: esp32_led_out_mb


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    id: pc_power_sensor
    name: "Power State"
    device_class: running
    icon: "mdi:desktop-classic"
    on_press:
      # When the PC turns ON
      then:
        - output.turn_on: esp32_led_out_mb
    on_release:
    #   # When the PC turns OFF
      then:
        - output.turn_off: esp32_led_out_mb


  - platform: template
    name: "Power Button Lock"
    id: power_button_lock
    device_class: safety
    entity_category: config
    lambda: |-
      return id(child_lock);

  - platform: gpio
    pin:
      number: GPIO3
      inverted: true
      mode:
        input: true
        pullup: true
    id: esp32_reset_in_mb
    name: "Reset Sensor (Case)"
    on_press:
      then:
        - if:
            condition:
              lambda: 'return !id(child_lock);'
            then:
              - switch.toggle: reset_switch
              - delay: 1000ms
              - switch.turn_off: reset_switch

            else:
              - logger.log: "Power button locked – reset press ignored"

  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
      mode:
        input: true
        pullup: true
    id: esp32_power_in_mb
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    name: "Power Button (Case)"
    on_press:
      then:
        - if:
            condition:
              lambda: 'return !id(child_lock);'
            then:
              - switch.toggle: power_switch
              - delay: 1000ms
              - switch.turn_off: power_switch
            else:
              - logger.log: "Power button locked – reset press ignored"


button:
  - platform: template
    name: "Power Button"
    id: power_button
    icon: "mdi:power-standby"
    on_press:
      then:
        - if:
            condition:
              lambda: 'return !id(child_lock);'
            then:
              - switch.turn_on: power_switch
              - delay: 1000ms
              - switch.turn_off: power_switch

  - platform: template
    name: "Force Power Off"
    id: force_power_off
    icon: "mdi:power-plug-off"
    on_press:
      then:
        - switch.turn_on: power_switch_force
        - delay: 5000ms
        - switch.turn_off: power_switch_force

  - platform: template
    name: "PC Reset"
    id: reset_button
    icon: "mdi:restart"
    on_press:
      then:
        - switch.toggle: reset_switch
        - switch.turn_on: reset_switch
        - delay: 1000ms
        - switch.turn_off: reset_switch

